version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:16.0.0
      - image: selenium/standalone-chrome:3.11.0
      - image: cimg/node:15.0.1-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Run Tests
          command: ./gradlew test
#      - run:
#          name: Save Test Results
#          command: |
#            mkdir -p ~/test-results/junit/
#            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
#          when: always
#      - store_test_results:
#          path: ~/test-results
#      - run:
#          name: Compress Artifacts
#          command: tar -cvzf gradle-test-report.tar .*/build/reports/tests/test/
#      - store_artifacts:
#          path: gradle-test-report.tar
#          destination: gradle-test-report.tar


workflows:
  version: 2
  test-tray-workflow:
    jobs:
      - build-and-test
  zero-minute-schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-test
#  fifteen-minute-schedule-workflow:
#    triggers:
#      - schedule:
#          cron: "15 * * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - build-and-test
#  thirty-minute-schedule-workflow:
#    triggers:
#      - schedule:
#          cron: "30 * * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - build-and-test
#  fourty-five-minute-schedule-workflow:
#    triggers:
#      - schedule:
#          cron: "45 * * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - build-and-test