version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:16.0.0
      - image: selenium/standalone-chrome:3.11.0
      - image: cimg/node:15.0.1-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Save Test Results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

workflows:
  test-tray-workflow:
    jobs:
- build-and-test